version: "3.8"

services:
  nginx:
    build:
      context: ./infra/docker/nginx
    depends_on:
      - php
    ports:
      - 8090:80
    volumes:
      - ./backend:/apps/kurogoma/backend:cached
  php:
    build:
      context: ./infra/docker/php
    volumes:
      - ./backend:/apps/kurogoma/backend:cached
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kurogoma
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 33062:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
  web:
    build:
      context: ./
      dockerfile: ./infra/docker/web/Dockerfile
    ports:
      - 3333:3333
    privileged: true
    volumes:
      - ./frontend:/app:cached
      - ./frontend/node_modules:/web/node_modules
    working_dir: /web
    tty: true
    stdin_open: true
    command: yarn dev

volumes:
  mysql_data:
  node_modules:
